export type ProviderCategory = 'text' | 'image' | 'video' | 'audio' | 'multimodal' | 'code';

export interface Provider {
  id: string;
  name: string;
  company: string;
  domain: string;
  description: string;
  models: string[];
  category: ProviderCategory;
  contextWindow?: string;
  tags: string[];
  placeholderKey: string;
  badge?: string;
  free?: boolean;
}

export const PROVIDERS: Provider[] = [
  // ── LANGUAGE / TEXT ─────────────────────────────────────────────────────
  {
    id: 'openai-gpt4o',
    name: 'GPT-4o',
    company: 'OpenAI',
    domain: 'openai.com',
    description: 'Most capable multimodal model — vision, reasoning & code',
    models: ['gpt-4o', 'gpt-4o-mini', 'gpt-4-turbo', 'gpt-3.5-turbo'],
    category: 'multimodal',
    contextWindow: '128K',
    tags: ['Popular', 'Vision', 'Fast'],
    placeholderKey: 'sk-...',
    badge: 'Popular',
  },
  {
    id: 'anthropic-claude',
    name: 'Claude 3.5',
    company: 'Anthropic',
    domain: 'anthropic.com',
    description: 'Most intelligent model — safe, harmless & helpful',
    models: ['claude-3-5-sonnet-20241022', 'claude-3-opus-20240229', 'claude-3-haiku-20240307'],
    category: 'text',
    contextWindow: '200K',
    tags: ['Safe', 'Coding', 'Long Context'],
    placeholderKey: 'sk-ant-...',
    badge: 'Top Pick',
  },
  {
    id: 'google-gemini',
    name: 'Gemini 2.5',
    company: 'Google',
    domain: 'gemini.google.com',
    description: "Google's most capable multimodal AI with 1M context window",
    models: ['gemini-2.5-pro', 'gemini-2.5-flash', 'gemini-1.5-pro', 'gemini-1.5-flash'],
    category: 'multimodal',
    contextWindow: '1M',
    tags: ['Free', 'Multimodal', '1M Context'],
    placeholderKey: 'AIza...',
    badge: 'Free',
    free: true,
  },
  {
    id: 'meta-llama',
    name: 'Llama 3.3',
    company: 'Meta',
    domain: 'meta.com',
    description: "Meta's open-source frontier model — free & powerful",
    models: ['llama-3.3-70b-instruct', 'llama-3.1-405b-instruct', 'llama-3.1-8b-instruct'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Open Source', 'Free', 'Coding'],
    placeholderKey: 'llama-...',
    badge: 'Open Source',
    free: true,
  },
  {
    id: 'mistral-ai',
    name: 'Mistral Large',
    company: 'Mistral AI',
    domain: 'mistral.ai',
    description: 'European frontier model with exceptional code expertise',
    models: ['mistral-large-latest', 'mistral-small-latest', 'codestral-latest', 'mistral-nemo'],
    category: 'text',
    contextWindow: '128K',
    tags: ['European', 'Fast', 'Coding'],
    placeholderKey: 'api-key-...',
  },
  {
    id: 'groq',
    name: 'Groq Speed',
    company: 'Groq',
    domain: 'groq.com',
    description: 'Ultra-fast LPU inference — 300 tokens/sec, near-instant responses',
    models: [
      'llama-3.3-70b-versatile',
      'mixtral-8x7b-32768',
      'gemma2-9b-it',
      'llama-3.1-8b-instant',
    ],
    category: 'text',
    contextWindow: '32K',
    tags: ['Ultra Fast', 'Free Tier', 'LPU'],
    placeholderKey: 'gsk_...',
    badge: 'Fastest',
    free: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    company: 'Perplexity AI',
    domain: 'perplexity.ai',
    description: 'AI with real-time web search & citation capabilities',
    models: [
      'llama-3.1-sonar-large-128k-online',
      'llama-3.1-sonar-small-128k-online',
      'llama-3.1-sonar-huge-128k-online',
    ],
    category: 'text',
    contextWindow: '128K',
    tags: ['Web Search', 'Real-time', 'Citations'],
    placeholderKey: 'pplx-...',
  },
  {
    id: 'deepseek',
    name: 'DeepSeek R1',
    company: 'DeepSeek',
    domain: 'deepseek.com',
    description: 'Advanced reasoning model with chain-of-thought thinking',
    models: ['deepseek-reasoner', 'deepseek-chat', 'deepseek-coder-v2'],
    category: 'text',
    contextWindow: '64K',
    tags: ['Reasoning', 'Coding', 'Math'],
    placeholderKey: 'sk-...',
    badge: 'New',
  },
  {
    id: 'xai-grok',
    name: 'Grok 3',
    company: 'xAI',
    domain: 'x.ai',
    description: "xAI's witty assistant with real-time X/Twitter data access",
    models: ['grok-3', 'grok-3-mini', 'grok-2-1212'],
    category: 'text',
    contextWindow: '131K',
    tags: ['Witty', 'Real-time X', 'Unfiltered'],
    placeholderKey: 'xai-...',
  },
  {
    id: 'cohere',
    name: 'Command R+',
    company: 'Cohere',
    domain: 'cohere.com',
    description: 'Enterprise RAG model with 128K context and embeddings',
    models: ['command-r-plus-08-2024', 'command-r-08-2024', 'command-light'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Enterprise', 'RAG', 'Embeddings'],
    placeholderKey: 'co-...',
  },
  {
    id: 'together-ai',
    name: 'Together AI',
    company: 'Together AI',
    domain: 'together.ai',
    description: 'Run 100+ open-source models with one unified API',
    models: ['meta-llama/Meta-Llama-3.1-70B', 'mistralai/Mixtral-8x22B', 'Qwen/Qwen2.5-72B'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Hub', 'Fast', 'Affordable'],
    placeholderKey: 'tog-...',
  },
  {
    id: 'ai21-labs',
    name: 'Jamba 1.5',
    company: 'AI21 Labs',
    domain: 'ai21.com',
    description: 'Mamba-Transformer hybrid with massive 256K context window',
    models: ['jamba-1.5-large', 'jamba-1.5-mini', 'j2-ultra'],
    category: 'text',
    contextWindow: '256K',
    tags: ['Hybrid', 'Long Context', 'Enterprise'],
    placeholderKey: 'ai21-...',
  },
  {
    id: 'qwen',
    name: 'Qwen 2.5',
    company: 'Alibaba',
    domain: 'aliyun.com',
    description: "Alibaba's frontier bilingual AI — Chinese & English expert",
    models: ['qwen-2.5-72b-instruct', 'qwen-2.5-32b-instruct', 'qwen-max'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Bilingual', 'Long Context', 'Affordable'],
    placeholderKey: 'sk-...',
    badge: 'New',
  },
  {
    id: 'microsoft-phi',
    name: 'Phi-4',
    company: 'Microsoft',
    domain: 'microsoft.com',
    description: "Microsoft's small but mighty reasoning model — SLM champion",
    models: ['phi-4', 'phi-3.5-mini-instruct', 'phi-3-medium-128k-instruct'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Small', 'Fast', 'Efficient'],
    placeholderKey: 'phi-...',
    badge: 'Efficient',
  },
  {
    id: 'google-gemma',
    name: 'Gemma 3',
    company: 'Google',
    domain: 'google.com',
    description: "Google's open-source lightweight models for on-device AI",
    models: ['gemma-3-27b-it', 'gemma-3-9b-it', 'gemma-2-9b-it'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Open Source', 'Lightweight', 'Free'],
    placeholderKey: 'gemma-...',
    free: true,
  },
  {
    id: 'upstage-solar',
    name: 'Solar Pro',
    company: 'Upstage',
    domain: 'upstage.ai',
    description: 'Korean AI powerhouse with stellar multilingual capabilities',
    models: ['solar-pro', 'solar-1-mini-chat', 'solar-1-mini-answer'],
    category: 'text',
    contextWindow: '32K',
    tags: ['Korean', 'Multilingual', 'Fast'],
    placeholderKey: 'up-...',
  },
  {
    id: 'moonshot-kimi',
    name: 'Kimi AI',
    company: 'Moonshot AI',
    domain: 'moonshot.cn',
    description: 'Long-context specialist with unparalleled 128K understanding',
    models: ['moonshot-v1-128k', 'moonshot-v1-32k', 'moonshot-v1-8k'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Long Context', 'Chinese', 'Affordable'],
    placeholderKey: 'sk-...',
  },
  {
    id: 'inflection-pi',
    name: 'Pi',
    company: 'Inflection AI',
    domain: 'inflection.ai',
    description: 'Personal AI with emotional intelligence & warmth',
    models: ['inflection-3-pi', 'inflection-3-productivity'],
    category: 'text',
    contextWindow: '128K',
    tags: ['Personal', 'Emotional', 'Friendly'],
    placeholderKey: 'inf-...',
  },
  {
    id: 'aleph-alpha',
    name: 'Luminous',
    company: 'Aleph Alpha',
    domain: 'aleph-alpha.com',
    description: 'European sovereign AI with strict data privacy & GDPR compliance',
    models: ['luminous-supreme-control', 'luminous-extended', 'luminous-base'],
    category: 'text',
    contextWindow: '96K',
    tags: ['European', 'GDPR', 'Sovereign'],
    placeholderKey: 'aa-...',
  },
  {
    id: 'nvidia-nim',
    name: 'NVIDIA NIM',
    company: 'NVIDIA',
    domain: 'nvidia.com',
    description: 'GPU-accelerated inference microservices — blazing fast',
    models: ['nvidia/llama-3.1-nemotron-70b', 'mistralai/mixtral-8x22b', 'nvidia/neva-22b'],
    category: 'multimodal',
    contextWindow: '128K',
    tags: ['GPU', 'Fast', 'Enterprise'],
    placeholderKey: 'nvapi-...',
  },

  // ── CODE ─────────────────────────────────────────────────────────────────
  {
    id: 'code-llama',
    name: 'Code Llama',
    company: 'Meta',
    domain: 'meta.com',
    description: "Meta's dedicated code generation model — 100+ programming languages",
    models: ['codellama-70b-instruct', 'codellama-34b-instruct', 'codellama-13b-instruct'],
    category: 'code',
    contextWindow: '100K',
    tags: ['Coding', 'Open Source', 'Free'],
    placeholderKey: 'code-llama-...',
    badge: 'Code',
    free: true,
  },
  {
    id: 'deepseek-coder',
    name: 'DeepSeek Coder',
    company: 'DeepSeek',
    domain: 'deepseek.com',
    description: 'World-class code model trained on 2T tokens of code data',
    models: ['deepseek-coder-v2', 'deepseek-coder-33b-instruct', 'deepseek-coder-6.7b-instruct'],
    category: 'code',
    contextWindow: '128K',
    tags: ['Coding', 'Fast', 'Multi-language'],
    placeholderKey: 'sk-...',
    badge: 'Code',
  },
  {
    id: 'codestral',
    name: 'Codestral',
    company: 'Mistral AI',
    domain: 'mistral.ai',
    description: "Mistral's code specialist — 80+ languages + fill-in-middle",
    models: ['codestral-latest', 'codestral-mamba-latest'],
    category: 'code',
    contextWindow: '32K',
    tags: ['Coding', 'Fast', 'Fill-in-Middle'],
    placeholderKey: 'api-key-...',
    badge: 'Code',
  },
  {
    id: 'starcoder',
    name: 'StarCoder 2',
    company: 'Hugging Face',
    domain: 'huggingface.co',
    description: 'Open-source code LLM trained on 600+ programming languages',
    models: ['starcoder2-15b', 'starcoder2-7b', 'starcoder2-3b'],
    category: 'code',
    contextWindow: '16K',
    tags: ['Open Source', 'Free', '600+ Languages'],
    placeholderKey: 'hf_...',
    badge: 'Open Source',
    free: true,
  },
  {
    id: 'wizard-coder',
    name: 'WizardCoder',
    company: 'Microsoft',
    domain: 'microsoft.com',
    description: 'Fine-tuned Code Llama model with enhanced instruction following',
    models: ['wizardcoder-34b-v1.0', 'wizardcoder-python-34b-v1.0', 'wizardcoder-15b-v1.0'],
    category: 'code',
    contextWindow: '16K',
    tags: ['Coding', 'Python', 'Instruction'],
    placeholderKey: 'wiz-...',
    free: true,
  },

  // ── MULTIMODAL ───────────────────────────────────────────────────────────
  {
    id: 'huggingface',
    name: 'Hugging Face',
    company: 'Hugging Face',
    domain: 'huggingface.co',
    description: 'Access 500K+ open-source models with one simple API',
    models: ['meta-llama/Meta-Llama-3-70B', 'mistralai/Mistral-7B-Instruct', 'google/gemma-7b-it'],
    category: 'multimodal',
    contextWindow: 'Varies',
    tags: ['Hub', 'Open Source', 'Research'],
    placeholderKey: 'hf_...',
    free: true,
  },
  {
    id: 'replicate',
    name: 'Replicate',
    company: 'Replicate',
    domain: 'replicate.com',
    description: 'Deploy & run any ML model — vision, audio, video, text',
    models: ['meta/llama-2-70b-chat', 'stability-ai/sdxl', 'anotherjesse/zeroscope-v2-xl'],
    category: 'multimodal',
    contextWindow: 'Varies',
    tags: ['ML Models', 'Image', 'Video'],
    placeholderKey: 'r8_...',
  },
  {
    id: 'amazon-bedrock',
    name: 'AWS Bedrock',
    company: 'Amazon',
    domain: 'aws.amazon.com',
    description: 'Managed AI with 30+ foundation models & enterprise SLA',
    models: ['anthropic.claude-3-5-sonnet', 'amazon.titan-text-premier', 'meta.llama3-70b'],
    category: 'multimodal',
    contextWindow: '200K',
    tags: ['Enterprise', 'Managed', 'AWS'],
    placeholderKey: 'AKIA...',
  },
  {
    id: 'azure-openai',
    name: 'Azure OpenAI',
    company: 'Microsoft',
    domain: 'azure.microsoft.com',
    description: 'Enterprise OpenAI models with Microsoft compliance & SLA',
    models: ['gpt-4o', 'gpt-4-turbo', 'gpt-35-turbo'],
    category: 'multimodal',
    contextWindow: '128K',
    tags: ['Enterprise', 'Compliance', 'Microsoft'],
    placeholderKey: 'azure-key-...',
  },
  {
    id: 'vertex-ai',
    name: 'Vertex AI',
    company: 'Google Cloud',
    domain: 'cloud.google.com',
    description: 'Google Cloud managed AI with Gemini Ultra & Palm2 models',
    models: ['gemini-2.0-flash', 'gemini-1.5-pro', 'text-bison'],
    category: 'multimodal',
    contextWindow: '1M',
    tags: ['GCP', 'Enterprise', 'Managed'],
    placeholderKey: 'ya29...',
  },

  // ── IMAGE GENERATION ─────────────────────────────────────────────────────
  {
    id: 'dalle3',
    name: 'DALL-E 3',
    company: 'OpenAI',
    domain: 'openai.com',
    description: "OpenAI's most photorealistic image generation model",
    models: ['dall-e-3', 'dall-e-2'],
    category: 'image',
    tags: ['Image Gen', 'Precise', 'Creative'],
    placeholderKey: 'sk-...',
    badge: 'Popular',
  },
  {
    id: 'stability-ai',
    name: 'Stable Diffusion',
    company: 'Stability AI',
    domain: 'stability.ai',
    description: 'Industry-leading open-source image generation models',
    models: ['stable-diffusion-3.5-large', 'stable-image-ultra', 'stable-diffusion-xl-1024-v1-0'],
    category: 'image',
    tags: ['Image Gen', 'Open Source', 'Art'],
    placeholderKey: 'sk-...',
  },
  {
    id: 'midjourney',
    name: 'Midjourney',
    company: 'Midjourney',
    domain: 'midjourney.com',
    description: "World's most artistic AI image generation platform",
    models: ['midjourney-v6.1', 'midjourney-v6', 'niji-6'],
    category: 'image',
    tags: ['Artistic', 'Photorealistic', 'Popular'],
    placeholderKey: 'mj-...',
    badge: 'Art',
  },
  {
    id: 'flux',
    name: 'Flux 1.1',
    company: 'Black Forest Labs',
    domain: 'blackforestlabs.ai',
    description: 'Next-gen image model from Stable Diffusion creators — ultra realistic',
    models: ['flux-1.1-pro', 'flux-1-pro', 'flux-1-dev', 'flux-1-schnell'],
    category: 'image',
    tags: ['Ultra Realistic', 'Fast', 'New'],
    placeholderKey: 'flux-...',
    badge: 'New',
  },
  {
    id: 'ideogram',
    name: 'Ideogram',
    company: 'Ideogram AI',
    domain: 'ideogram.ai',
    description: 'Best text-in-image AI — perfect for logos and typography art',
    models: ['ideogram-v2', 'ideogram-v2-turbo', 'ideogram-v1'],
    category: 'image',
    tags: ['Text in Image', 'Logos', 'Typography'],
    placeholderKey: 'ideo-...',
    badge: 'Text Art',
  },
  {
    id: 'leonardo-ai',
    name: 'Leonardo AI',
    company: 'Leonardo AI',
    domain: 'leonardo.ai',
    description: 'AI creative studio for concept art, game assets & design',
    models: ['phoenix', 'lightning-xl', 'vision-xl', 'kino-xl'],
    category: 'image',
    tags: ['Game Art', 'Concept Art', 'Creative'],
    placeholderKey: 'leo-...',
  },
  {
    id: 'adobe-firefly',
    name: 'Adobe Firefly',
    company: 'Adobe',
    domain: 'firefly.adobe.com',
    description: "Adobe's commercially safe generative AI for creative pros",
    models: ['firefly-image-3', 'firefly-image-2', 'firefly-image-1'],
    category: 'image',
    tags: ['Commercial Safe', 'Creative', 'Adobe'],
    placeholderKey: 'adobe-...',
  },
  {
    id: 'playground-ai',
    name: 'Playground v3',
    company: 'Playground AI',
    domain: 'playground.com',
    description: 'Free image generation — aesthetic, graphic design focused',
    models: ['playground-v3', 'playground-v2.5'],
    category: 'image',
    tags: ['Free', 'Design', 'Aesthetic'],
    placeholderKey: 'pg-...',
    badge: 'Free',
    free: true,
  },

  // ── VIDEO GENERATION ─────────────────────────────────────────────────────
  {
    id: 'runway-ml',
    name: 'Runway Gen-3',
    company: 'Runway',
    domain: 'runway.ml',
    description: 'State-of-the-art AI video generation & film editing',
    models: ['gen-3-alpha', 'gen-3-alpha-turbo', 'gen-2'],
    category: 'video',
    tags: ['Video Gen', 'High Quality', 'Film'],
    placeholderKey: 'rw-...',
    badge: 'Studio',
  },
  {
    id: 'pika-labs',
    name: 'Pika 2.0',
    company: 'Pika Labs',
    domain: 'pika.art',
    description: 'Fast and accessible AI video generation for everyone',
    models: ['pika-2.0', 'pika-1.5', 'pika-1.0'],
    category: 'video',
    tags: ['Video Gen', 'Fast', 'Affordable'],
    placeholderKey: 'pika-...',
  },
  {
    id: 'luma-ai',
    name: 'Dream Machine',
    company: 'Luma AI',
    domain: 'lumalabs.ai',
    description: '5-second cinematic videos from text or image prompts',
    models: ['dream-machine-1.5', 'dream-machine-1.0'],
    category: 'video',
    tags: ['Video Gen', 'Cinematic', 'Fast'],
    placeholderKey: 'luma-...',
    badge: 'New',
  },
  {
    id: 'kling-ai',
    name: 'Kling AI',
    company: 'Kuaishou',
    domain: 'klingai.com',
    description: 'Chinese AI video model — 1080p, up to 3 minutes long',
    models: ['kling-v1.6-pro', 'kling-v1.6-standard', 'kling-v1'],
    category: 'video',
    tags: ['Video Gen', 'Long Video', '1080p'],
    placeholderKey: 'kling-...',
    badge: 'Long Video',
  },
  {
    id: 'sora-openai',
    name: 'Sora',
    company: 'OpenAI',
    domain: 'openai.com',
    description: "OpenAI's breakthrough text-to-video — up to 1 minute HD",
    models: ['sora-1', 'sora-turbo'],
    category: 'video',
    tags: ['Video Gen', 'High Quality', 'OpenAI'],
    placeholderKey: 'sk-...',
    badge: 'Breakthrough',
  },
  {
    id: 'minimax-video',
    name: 'Hailuo AI',
    company: 'MiniMax',
    domain: 'hailuoai.com',
    description: 'High-quality AI video with smooth motion and consistency',
    models: ['video-01', 'video-01-live2d'],
    category: 'video',
    tags: ['Video Gen', 'Smooth Motion', 'Chinese'],
    placeholderKey: 'minimax-...',
  },

  // ── AUDIO GENERATION ─────────────────────────────────────────────────────
  {
    id: 'elevenlabs',
    name: 'ElevenLabs',
    company: 'ElevenLabs',
    domain: 'elevenlabs.io',
    description: 'Most realistic AI voice cloning & TTS globally',
    models: ['eleven_turbo_v2_5', 'eleven_multilingual_v2', 'eleven_monolingual_v1'],
    category: 'audio',
    tags: ['Voice', 'TTS', 'Multilingual'],
    placeholderKey: 'el-...',
    badge: 'Best Voice',
  },
  {
    id: 'suno',
    name: 'Suno',
    company: 'Suno AI',
    domain: 'suno.ai',
    description: 'Create full AI songs with vocals, instruments and lyrics',
    models: ['suno-v4', 'suno-v3.5', 'suno-v3'],
    category: 'audio',
    tags: ['Music Gen', 'Vocals', 'Full Songs'],
    placeholderKey: 'suno-...',
    badge: 'Music',
  },
  {
    id: 'udio',
    name: 'Udio',
    company: 'Udio',
    domain: 'udio.com',
    description: 'AI music generation — any genre, any style, any mood',
    models: ['udio-130', 'udio-32'],
    category: 'audio',
    tags: ['Music Gen', 'Any Genre', 'High Quality'],
    placeholderKey: 'udio-...',
    badge: 'Music',
  },
  {
    id: 'musicgen-meta',
    name: 'MusicGen',
    company: 'Meta',
    domain: 'meta.com',
    description: "Meta's open-source music generation — text to music in seconds",
    models: ['musicgen-large', 'musicgen-melody', 'musicgen-stereo-large'],
    category: 'audio',
    tags: ['Music Gen', 'Open Source', 'Free'],
    placeholderKey: 'musicgen-...',
    badge: 'Open Source',
    free: true,
  },
  {
    id: 'openai-tts',
    name: 'OpenAI TTS',
    company: 'OpenAI',
    domain: 'openai.com',
    description: 'Natural TTS with 6 distinct voice personalities in HD',
    models: ['tts-1-hd', 'tts-1'],
    category: 'audio',
    tags: ['TTS', '6 Voices', 'Fast'],
    placeholderKey: 'sk-...',
  },
  {
    id: 'openai-whisper',
    name: 'Whisper',
    company: 'OpenAI',
    domain: 'openai.com',
    description: 'OpenAI speech recognition — transcribe & translate audio',
    models: ['whisper-1', 'whisper-large-v3', 'whisper-medium'],
    category: 'audio',
    tags: ['Speech-to-Text', 'Transcription', 'Translation'],
    placeholderKey: 'sk-...',
  },
  {
    id: 'play-ai',
    name: 'PlayAI',
    company: 'PlayAI',
    domain: 'play.ai',
    description: 'Ultra-realistic conversational AI voice with emotional range',
    models: ['playai-tts-1', 'play3.0-mini'],
    category: 'audio',
    tags: ['Voice Clone', 'Emotional', 'Conversational'],
    placeholderKey: 'play-...',
  },
  {
    id: 'google-tts',
    name: 'Google TTS',
    company: 'Google',
    domain: 'cloud.google.com',
    description: 'Google Cloud TTS — 380+ voices in 50+ languages',
    models: ['en-US-Neural2-A', 'en-US-Studio-O', 'en-US-Wavenet-F'],
    category: 'audio',
    tags: ['TTS', '380+ Voices', 'Multilingual'],
    placeholderKey: 'AIza...',
  },
];

export const CATEGORY_LABELS: Record<string, string> = {
  all: 'All',
  text: 'Language',
  multimodal: 'Multimodal',
  code: 'Code',
  image: 'Image',
  video: 'Video',
  audio: 'Audio',
};

export const PROMPT_TEMPLATES = [
  {
    id: 'html-app',
    label: 'Build a Web App',
    prompt:
      'Build a complete, beautiful [APP NAME] web app using HTML, CSS, and JavaScript. Make it fully functional with modern design.',
  },
  {
    id: 'react-component',
    label: 'React Component',
    prompt:
      'Create a complete React component for [COMPONENT NAME]. Include state, styling, and all edge cases.',
  },
  {
    id: 'explain',
    label: 'Explain a Concept',
    prompt: 'Explain [TOPIC] simply with clear examples and analogies for a beginner.',
  },
  {
    id: 'code-review',
    label: 'Code Review',
    prompt: 'Review this code for bugs, performance, and best practices:\n\n```\n[CODE]\n```',
  },
  {
    id: 'debug',
    label: 'Debug Code',
    prompt: 'Find and fix the bug. Explain what was wrong:\n\n```\n[CODE]\n```',
  },
  {
    id: 'write-email',
    label: 'Write an Email',
    prompt: 'Write a professional email about [TOPIC]. Tone: [TONE]. Be concise.',
  },
  {
    id: 'brainstorm',
    label: 'Brainstorm Ideas',
    prompt: 'Brainstorm 10 creative ideas for [TOPIC]. Be innovative and diverse.',
  },
  { id: 'summarize', label: 'Summarize Text', prompt: 'Summarize in 3-5 bullet points:\n\n[TEXT]' },
  {
    id: 'translate',
    label: 'Translate',
    prompt: 'Translate to [LANGUAGE], maintaining tone:\n\n[TEXT]',
  },
  {
    id: 'write-story',
    label: 'Write a Story',
    prompt: 'Write a short story about [TOPIC]. Genre: [GENRE]. Make it engaging.',
  },
  {
    id: 'seo',
    label: 'SEO Content',
    prompt: 'Write SEO-optimized content for [TOPIC] with H1, H2 and keywords.',
  },
  {
    id: 'social-post',
    label: 'Social Media Post',
    prompt: 'Write an engaging [PLATFORM] post about [TOPIC]. Make it shareable.',
  },
];

export const KEYBOARD_SHORTCUTS = [
  { key: '⌘ + Enter', description: 'Send message' },
  { key: 'Shift + Enter', description: 'New line' },
  { key: '⌘ + K', description: 'New conversation' },
  { key: '⌘ + B', description: 'Toggle sidebar' },
  { key: '⌘ + E', description: 'Export conversation' },
  { key: '/', description: 'Open command menu' },
  { key: 'Esc', description: 'Close modals' },
];
